name: Lint

on: [pull_request]

jobs:
  merge-conflict:
    name: Merge Conflict
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check merge conflict
        run: grep "^<<<<<<< HEAD" $(git ls-files | xargs) && exit 1 || true
  gnuaspell:
    name: Check Spelling GNU Aspell Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          sudo apt update
          sudo apt-get install aspell
      - name: Run Markdown Spell Check
        run: bash ./check-spelling.sh || exit 1
  misspell:
    name: Check Spelling Misspell All Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: Misspell
        run: git ls-files --empty-directory | xargs ./misspell -error
  trailing-whitespace:
    name: Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for trailing whitespace
        run: "! git grep -EIn $'[ \t]+$'"
